fix the build with clang 20 (#210)
* [chore]: silence -Wimplicit-fallthrough warning in deps/yajl

when building with GCC 15.2.1, it complains:

```
/home/kefu/dev/pipy/deps/yajl-2.1.0/src/yajl_parser.c: In function ‘yajl_do_parse’:
/home/kefu/dev/pipy/deps/yajl-2.1.0/src/yajl_parser.c:334:24: warning: this statement may fall through [-Wimplicit-fallthrough=]
  334 |                     if (yajl_bs_current(hand->stateStack) ==
      |                        ^
/home/kefu/dev/pipy/deps/yajl-2.1.0/src/yajl_parser.c:347:17: note: here
  347 |                 case yajl_tok_colon:
      |                 ^~~~
/home/kefu/dev/pipy/deps/yajl-2.1.0/src/yajl_parser.c:405:24: warning: this statement may fall through [-Wimplicit-fallthrough=]
  405 |                     if (yajl_bs_current(hand->stateStack) ==
      |                        ^
/home/kefu/dev/pipy/deps/yajl-2.1.0/src/yajl_parser.c:414:17: note: here
  414 |                 default:
      |                 ^~~~~~~
```

let's silence it using the "fallthrough" attribute, see
https://gcc.gnu.org/onlinedocs/gcc/Statement-Attributes.html#index-fallthrough-statement-attribute
for its document.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

* [chore]: silence -Wdeprecated-literal-operator warning in deps/asio

when building the tree using Clang 20.1.8, it complains:

```
/home/kefu/dev/pipy/deps/asio-1.28.0/include/asio/buffer.hpp:2884:37: warning: identifier '_buf' preceded by whitespace in a literal operator declaration is deprecated [-Wdeprecated-literal-operator]
 2884 | inline ASIO_CONST_BUFFER operator"" _buf(const char* data, std::size_t n)
      |                          ~~~~~~~~~~~^~~~
      |                          operator""_buf
```

so let's remove the extraneous space.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

* [chore] include used header

when building the tree with the libstdc++ shipped along with GCC 15, the
compiler complains:

```
In file included from /home/kefu/dev/pipy/src/elf.cpp:26:
/home/kefu/dev/pipy/src/elf.hpp:51:11: error: unknown type name 'uint8_t'
   51 |     const uint8_t *data;
      |           ^
/home/kefu/dev/pipy/src/elf.hpp:102:19: error: use of undeclared identifier 'uint8_t'
  102 |   ELF(std::vector<uint8_t> &&data);
      |                   ^
/home/kefu/dev/pipy/src/elf.hpp:107:15: error: use of undeclared identifier 'uint8_t'
  107 |   std::vector<uint8_t> m_data;
      |               ^
/home/kefu/dev/pipy/src/elf.cpp:52:6: error: out-of-line definition of 'ELF' does not match any declaration in 'pipy::ELF'
   52 | ELF::ELF(std::vector<uint8_t> &&data) : m_data(std::move(data)) {
      |      ^~~
/home/kefu/dev/pipy/src/elf.hpp:40:7: note: ELF defined here
   40 | class ELF {
      |       ^~~
```

let's include the header where `uint8_t` is defined.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

---------

Signed-off-by: Kefu Chai <tchaikov@gmail.com>