[chore] include used header
when building the tree with the libstdc++ shipped along with GCC 15, the
compiler complains:

```
In file included from /home/kefu/dev/pipy/src/elf.cpp:26:
/home/kefu/dev/pipy/src/elf.hpp:51:11: error: unknown type name 'uint8_t'
   51 |     const uint8_t *data;
      |           ^
/home/kefu/dev/pipy/src/elf.hpp:102:19: error: use of undeclared identifier 'uint8_t'
  102 |   ELF(std::vector<uint8_t> &&data);
      |                   ^
/home/kefu/dev/pipy/src/elf.hpp:107:15: error: use of undeclared identifier 'uint8_t'
  107 |   std::vector<uint8_t> m_data;
      |               ^
/home/kefu/dev/pipy/src/elf.cpp:52:6: error: out-of-line definition of 'ELF' does not match any declaration in 'pipy::ELF'
   52 | ELF::ELF(std::vector<uint8_t> &&data) : m_data(std::move(data)) {
      |      ^~~
/home/kefu/dev/pipy/src/elf.hpp:40:7: note: ELF defined here
   40 | class ELF {
      |       ^~~
```

let's include the header where `uint8_t` is defined.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>